---
# tasks file to Verify OS
- name: Gathering  Version using NTC-Templates
  ansible.utils.cli_parse:
    command: "show version"
    parser:
      name: ansible.netcommon.ntc_templates
    set_fact: version_output

- name: Displaying version of target Switch
  ansible.builtin.debug:
    msg: "Version of {{ inventory_hostname }} is :  {{ version_output | community.general.json_query('[0].boot_image') }}"
  when: '"sw" in inventory_hostname'

- name: Displaying version of target Router
  ansible.builtin.debug:
    msg: "Version of {{ inventory_hostname }} is :  {{ version_output | community.general.json_query('[0].version') }}"
  when: '"dist-rtr" in inventory_hostname'
